### ISSUE TITLE
Buttons in front of the "window"

### ISSUE THREAD

**Issue by walbrc27** [walbrc27/cs341#4]
The window through which we see outer space has 3 buttons on it: Logout, Left Door, and Right Door. When you hover the mouse over these buttons, they nearly vanish (they become like 95% transparent). I think this is an XML issue.

**Comment by gardng59** [comment]
I do not have this issue when I try it. Did someone else do it?

**Comment by walbrc27** [comment]
Interesting. I was having this issue previously, but maybe someone DID fix it. I will test it tomorrow.

**Comment by calewis1995** [comment]
It becomes a semi-transparent bluish color when you hover over it. You can see the text fine. So I don't find it a big deal.

**Comment by walbrc27** [comment]
I have reopened this issue because though the buttons are still legible, they are unpleasantly hard to see.

**Comment by calewis1995** [comment]
Ok, so I fixed half of the problem. The buttons no longer stay transparent after you click it (the most important part). However, when hovering the mouse over the button, it still does that. And that is due to the fact that that's what happens with mouse hovering, it highlights the button a light blue (or another color depending on background color of the button).  It looks weird for us because of our background pictures of space and the farm (a little). The power room looks fine because of the orange background.

**Comment by walbrc27** [comment]
Thanks for what seems to be dedicated troubleshooting of the issue, Cory. I will close the issue as it no longer poses a serious threat to our grade.
